apiVersion: v1
kind: Service
metadata:
  name: windows-2025
  namespace: windows-2025
spec:
  type: NodePort
  selector:
    app: windows-2025
  ports:
    - name: tcp-8006
      protocol: TCP
      port: 8006
      targetPort: 8006
      nodePort: 32025
    - name: tcp-3389
      protocol: TCP
      port: 3389
      targetPort: 3389
    - name: udp-3389
      protocol: UDP
      port: 3389
      targetPort: 3389
